apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: awsaws-sjsj
  project: shobhit
spec:
  blueprintConfig:
    name: minimal
    version: 4.0.0
  cloudCredentials: aws-cred-shobhit-raut
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
    addons:
    - name: coredns
      version: v1.11.4-eksbuild.2
    - name: vpc-cni
      version: v1.20.4-eksbuild.2
    - name: kube-proxy
      version: v1.32.6-eksbuild.12
    - name: aws-ebs-csi-driver
      version: latest
    addonsConfig: {}
    autoModeConfig: {}
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 2
      name: managed-ng-1
      version: "1.32"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: awsaws-sjsj
      region: us-east-1
      version: "1.32"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
