apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: gcp-1-sjsj
  project: shobhit
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: gke
  config:
    controlPlaneVersion: "1.36"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: qa-automation-371111
    location:
      config:
        zone: us-central1-c
      type: zonal
    network:
      access:
        config: null
        type: public
      dataPlaneV2: ADVANCED_DATAPATH
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      management:
        autoUpgrade: true
      name: default-nodepool
      nodeVersion: "1.35"
      size: 3
      upgradeSettings:
        config:
          maxSurge: 1
        strategy: SURGE
    releaseChannel:
      channel: EXTENDED
  sharing:
    enabled: true
    projects:
    - name: shobhittest1
  type: gke
