apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: prometheus-shobhit
  project: shobhit
spec:
  blueprintConfig:
    name: default-aks
  cloudCredentials: shobhit_azure2
  config:
    kind: aksClusterConfig
    metadata:
      name: prometheus-shobhit
    spec:
      managedCluster:
        apiVersion: "2025-05-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          autoUpgradeProfile:
            nodeOsUpgradeChannel: None
            upgradeChannel: none
          disableLocalAccounts: false
          dnsPrefix: prometheus-shobhit-dns
          enableRBAC: true
          kubernetesVersion: 1.34.7
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2025-05-01"
        name: primary
        properties:
          count: 5
          enableAutoScaling: true
          maxCount: 5
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.34.7
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
  type: aks
