apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: shobhit-local-account
  project: shobhit
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: shobhit_azure2
  config:
    kind: aksClusterConfig
    metadata:
      name: shobhit-local-account
    spec:
      managedCluster:
        additionalMetadata:
          acrProfile:
            registries:
            - acrName: shobhitfnfacr
              resourceGroupName: shobhit-fnf-cluster-rg
        apiVersion: "2024-01-01"
        identity:
          type: UserAssigned
          userAssignedIdentities:
            ? /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-fnf-cluster-identity
            : {}
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          autoUpgradeProfile:
            nodeOsUpgradeChannel: None
            upgradeChannel: none
          disableLocalAccounts: false
          dnsPrefix: shobhit-local-account-dns
          enableRBAC: true
          identityProfile:
            kubeletIdentity:
              resourceId: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-kubelet-identity
          kubernetesVersion: 1.29.13
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: standard
            networkPlugin: azure
            networkPluginMode: overlay
            networkPolicy: calico
            podCidr: 10.244.0.0/16
            serviceCidr: 10.0.0.0/16
          oidcIssuerProfile:
            enabled: true
          powerState:
            code: Running
          securityProfile:
            workloadIdentity:
              enabled: true
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.29.13
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: np2
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: User
          nodeLabels:
            env: qa
          nodeTaints:
          - key1=value1:PreferNoSchedule
          orchestratorVersion: 1.29.13
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: np3
        properties:
          count: 1
          enableAutoScaling: true
          kubeletConfig:
            containerLogMaxFiles: 2
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: User
          nodeLabels:
            env: qa
          nodeTaints:
          - key1=value1:PreferNoSchedule
          orchestratorVersion: 1.29.13
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
  type: aks
