apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: shobhitazure-nov21
  project: shobhit
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: shobhit_azure2
  config:
    kind: aksClusterConfig
    metadata:
      name: shobhitazure-nov21
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          autoUpgradeProfile:
            nodeOsUpgradeChannel: None
            upgradeChannel: none
          disableLocalAccounts: false
          dnsPrefix: shobhitazure-nov21-dns
          enableRBAC: true
          kubernetesVersion: 1.31.8
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
          powerState:
            code: Stopped
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.31.8
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
  type: aks
