apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: shobhit-2
  project: shobhit
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: shobhit_azure2
  config:
    kind: aksClusterConfig
    metadata:
      name: shobhit-2
    spec:
      managedCluster:
        apiVersion: "2023-11-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          aadProfile:
            enableAzureRBAC: true
            managed: true
          addonProfiles:
            azurePolicy:
              enabled: false
          autoUpgradeProfile:
            nodeOsUpgradeChannel: None
            upgradeChannel: none
          disableLocalAccounts: true
          dnsPrefix: shobhit-2-dns
          enableRBAC: true
          identityProfile:
            kubeletIdentity:
              resourceId: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourcegroups/MC_shobhit-rg_shobhit-2_centralindia/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-2-agentpool
          kubernetesVersion: 1.33.5
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: standard
            networkDataplane: azure
            networkPlugin: azure
            networkPluginMode: overlay
            podCidr: 10.244.0.0/16
            serviceCidr: 10.0.0.0/16
          nodeResourceGroup: MC_shobhit-rg_shobhit-2_centralindia
          oidcIssuerProfile:
            enabled: true
          powerState:
            code: Stopped
          securityProfile:
            workloadIdentity:
              enabled: true
          windowsProfile:
            adminUsername: azureuser
            enableCSIProxy: true
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2023-11-01"
        location: centralindia
        name: agentpool
        properties:
          availabilityZones:
          - "1"
          - "2"
          - "3"
          count: 2
          enableAutoScaling: true
          maxCount: 5
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.33.5
          osDiskSizeGB: 128
          osType: Linux
          type: VirtualMachineScaleSets
          upgradeSettings:
            maxSurge: 10%
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
  proxyConfig: {}
  type: aks
