apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: shobhit-prod
  project: shobhit
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: shobhit_azure2
  config:
    kind: aksClusterConfig
    metadata:
      name: shobhit-prod
    spec:
      managedCluster:
        additionalMetadata:
          acrProfile:
            registries:
            - acrName: shobhitfnfacr
              resourceGroupName: shobhit-fnf-cluster-rg
        apiVersion: "2024-01-01"
        identity:
          type: UserAssigned
          userAssignedIdentities:
            ? /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-fnf-cluster-identity
            : {}
        location: centralindia
        properties:
          aadProfile:
            adminGroupObjectIds:
            - e77135db-9039-42a5-a9db-c6afa3b84a9b
            managed: true
          addonProfiles:
            azureKeyvaultSecretsProvider:
              config:
                enableSecretRotation: "true"
                rotationPollInterval: 24m
              enabled: false
            azurePolicy:
              enabled: false
            httpApplicationRouting:
              enabled: true
            omsAgent:
              config:
                logAnalyticsWorkspaceResourceID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourcegroups/defaultresourcegroup-cin/providers/microsoft.operationalinsights/workspaces/DefaultWorkspace-a2252eb2-7a25-432b-a5ec-e18eba6f26b1-CIN
              enabled: true
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          autoScalerProfile:
            balance-similar-node-groups: "false"
            expander: random
            max-empty-bulk-delete: "10"
            max-graceful-termination-sec: "600"
            max-node-provision-time: 15m
            max-total-unready-percentage: "45"
            new-pod-scale-up-delay: 10s
            ok-total-unready-count: "3"
            scale-down-delay-after-add: 10m
            scale-down-delay-after-delete: 60s
            scale-down-delay-after-failure: 3m
            scale-down-unneeded-time: 10m
            scale-down-unready-time: 20m
            scale-down-utilization-threshold: "0.5"
            scan-interval: 10s
            skip-nodes-with-local-storage: "true"
            skip-nodes-with-system-pods: "true"
          autoUpgradeProfile:
            nodeOsUpgradeChannel: NodeImage
            upgradeChannel: patch
          disableLocalAccounts: true
          dnsPrefix: shobhit-prod-dns
          enableRBAC: true
          identityProfile:
            kubeletIdentity:
              resourceId: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-cluster-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shobhit-kubelet-identity
          kubernetesVersion: 1.29.11
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: standard
            networkPlugin: azure
            networkPluginMode: overlay
            networkPolicy: calico
            podCidr: 10.244.0.0/16
            serviceCidr: 10.0.0.0/16
          nodeResourceGroup: shobhit-node-rg-13feb
          oidcIssuerProfile:
            enabled: true
          powerState:
            code: Stopped
          securityProfile:
            workloadIdentity:
              enabled: true
        sku:
          name: Base
          tier: Free
        tags:
          email: shobhit@rafay.co
          env: qa
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          kubeletConfig:
            containerLogMaxFiles: 2
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.29.11
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: sec
        properties:
          count: 1
          enableAutoScaling: true
          kubeletConfig:
            containerLogMaxFiles: 2
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          nodeLabels:
            key1: val1
            key2: val2
          nodeTaints:
          - key1=value1:PreferNoSchedule
          - key2=value2:PreferNoSchedule
          orchestratorVersion: 1.29.11
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      - apiVersion: "2024-01-01"
        name: winnp
        properties:
          availabilityZones:
          - "1"
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 110
          minCount: 2
          mode: User
          orchestratorVersion: 1.29.11
          osType: Windows
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
          vnetSubnetID: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-fnf-nw-rg/providers/Microsoft.Network/virtualNetworks/shobhit-fnf-vnet/subnets/default
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
      workloadIdentities:
      - createIdentity: true
        metadata:
          location: centralindia
          name: shobhit-feb13-wissaas
          resourceGroup: shobhit-rg
          tags:
            email: shobhit@rafay.co
            env: qa
        roleAssignments:
        - name: Key Vault Secrets User
          scope: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-rg/providers/Microsoft.KeyVault/vaults/shobhitkeyvault2
        serviceAccounts:
        - createAccount: true
          metadata:
            annotations:
              ann1: val1
            labels:
              key1: val1
            name: sa-feb13sasasa
            namespace: default
  systemComponentsPlacement:
    nodeSelector:
      key1: val1
      key2: val2
    tolerations:
    - effect: PreferNoSchedule
      key: key1
      operator: Equal
      value: val1
    - effect: PreferNoSchedule
      key: key2
      operator: Equal
      value: val2
  type: aks
